help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	find . | grep -E ".coverage*" | xargs rm -rf
	rm -f .coverage

format: ## Run pre-commit hooks
	pre-commit run -a

sync: ## Merge changes from main branch to your current branch
	git pull
	git pull origin main

update-dev: ## Update development dependencies and pre-commit hooks
	poetry update --only dev
	pre-commit autoupdate

test: ## Run all tests
	pytest

build: ## Build docker image from dockerfile
	DOCKER_BUILDKIT=1 docker build --no-cache \
		-f Dockerfile \
		--network=host \
		-t django-site .

run: ## Create docker container from image and run
	docker run -dit \
		--name django-server \
		-p 127.0.0.1:8000:8080 \
		--network host \
		django-site python manage.py runserver 8000

start: ## Start created container
	docker start django-server

stop: ## Stop running container
	docker stop django-server
